//
//  AudioEngineModule.mm
//  micdrp
//
//  WP-AUDIO-BRIDGE — Tier-1 native audio engine (iOS).
//
//  Pipeline:
//    AVAudioEngine input tap (real-time audio thread)
//      -> feed Float32 frames into the shared C++ PitchEngine (cpp/dsp)
//      -> PitchEngine runs MPM (mpm.h) + note conversion (notes.h) over hops
//      -> emit throttled PitchSample dictionaries to JS via RCTEventEmitter
//    Raw PCM never crosses into JS. Captured audio is written to a .wav file
//    for the RecordingHandle uri; the full (un-throttled) analysis is returned
//    from stop().
//
//  The C++ DSP core is owned by WP-DSP-CORE under packages/client/cpp/dsp.
//  This file references only its public headers; the Podspec/Xcode project add
//  cpp/dsp/*.cpp to the compile sources (see docs/NATIVE_SETUP.md).
//

#import "AudioEngineModule.h"

#import "CaptureFile.h"

#import <AVFoundation/AVFoundation.h>
#import <UIKit/UIKit.h>
#import <React/RCTLog.h>

#include <atomic>
#include <chrono>
#include <memory>
#include <mutex>
#include <thread>
#include <vector>

// Shared C++ DSP core (WP-DSP-CORE): the mechanical port of packages/logic's
// MPM detector + note conversion (golden-parity tested against the TS oracle).
// The streaming shell lives there too. This bridge used to carry a second one
// of its own (ios/StreamingPitch.h), which is how a field added to the shared
// PitchSample never reached the app: the struct the app marshalled was the
// other one (INV-PITCH-021).
#include "pitch_engine.h"

using micdrp::dsp::EngineConfig;
using micdrp::dsp::PitchEngine;
using micdrp::dsp::PitchSample;


@implementation AudioEngineModule {
  AVAudioEngine *_engine;
  AVAudioFile *_captureFile;
  NSURL *_captureURL;

  std::shared_ptr<PitchEngine> _pitch;
  std::mutex _pitchMutex;          // guards _samples (NOT the ring: that is lock-free)
  std::vector<PitchSample> _samples;

  // Drains the engine off the audio thread. The audio callback only enqueues
  // PCM, which is lock-free and allocation-free; the analysis runs here, so a
  // slow window can never stall capture and put a gap in the recording.
  std::thread _drain;
  std::atomic<bool> _draining;

  EngineConfig _config;
  std::atomic<bool> _running;

  double _startHostTime;           // capture start, ms
  double _lastEmitMs;              // last throttled emit, ms
  NSString *_recordingId;
}

RCT_EXPORT_MODULE();

#pragma mark - lifecycle

- (instancetype)init {
  if (self = [super init]) {
    _config = EngineConfig{};  // C++ defaults mirror DEFAULT_ENGINE_CONFIG
    _running = false;
    _lastEmitMs = 0;
  }
  return self;
}

+ (BOOL)requiresMainQueueSetup {
  return NO;
}

/// Hands the JSI module to the TurboModule runtime. Generated by codegen from
/// src/specs/NativeAudioEngine.ts.
- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params {
  return std::make_shared<facebook::react::NativeAudioEngineSpecJSI>(params);
}

- (dispatch_queue_t)methodQueue {
  return dispatch_get_main_queue();
}

#pragma mark - helpers

- (void)emitState:(NSString *)state {
  [self emitOnState:state];
}

static double NowMs() {
  return (double)(CACurrentMediaTime() * 1000.0);
}

#pragma mark - exported methods

- (void)configure:(JS::NativeAudioEngine::EngineConfigInput &)config
          resolve:(RCTPromiseResolveBlock)resolve
           reject:(RCTPromiseRejectBlock)reject {
  @try {
    std::lock_guard<std::mutex> lock(_pitchMutex);
    // Every field is optional; an absent one leaves the current value alone.
    if (auto v = config.sampleRateHz()) _config.sampleRateHz = *v;
    if (auto v = config.frameSize()) _config.frameSize = (std::size_t)*v;
    if (auto v = config.hopSize()) _config.hopSize = (std::size_t)*v;
    if (auto v = config.minFrequencyHz()) _config.minFrequencyHz = *v;
    if (auto v = config.maxFrequencyHz()) _config.maxFrequencyHz = *v;
    if (auto v = config.clarityThreshold()) _config.clarityThreshold = *v;
    if (auto v = config.voicedClarityMin()) _config.voicedClarityMin = *v;
    if (auto v = config.voicedLevelDb()) _config.voicedLevelDb = *v;
    if (auto v = config.emitRateHz()) _config.emitRateHz = *v;
    resolve(nil);
  } @catch (NSException *e) {
    reject(@"configure_failed", e.reason, nil);
  }
}

- (void)requestPermission:(RCTPromiseResolveBlock)resolve
                   reject:(RCTPromiseRejectBlock)reject {
  AVAudioSession *session = [AVAudioSession sharedInstance];
  AVAudioSessionRecordPermission perm = [session recordPermission];
  if (perm == AVAudioSessionRecordPermissionGranted) {
    resolve(@YES);
    return;
  }
  if (perm == AVAudioSessionRecordPermissionDenied) {
    resolve(@NO);
    return;
  }
  [session requestRecordPermission:^(BOOL granted) {
    resolve(granted ? @YES : @NO);
  }];
}

- (void)start:(NSString *)captureDir
      overdub:(std::optional<bool>)overdub
      resolve:(RCTPromiseResolveBlock)resolve
       reject:(RCTPromiseRejectBlock)reject {
  if (_running.load()) {
    resolve(nil);
    return;
  }

  NSError *sessionErr = nil;
  AVAudioSession *session = [AVAudioSession sharedInstance];
  // Measurement strips every bit of processing, which is what a first take
  // wants — nothing between the voice and the detector. It is exactly wrong
  // for an overdub: it takes the session and silences what is playing, and
  // with no echo cancellation the microphone hears the take through the
  // speaker, so the detector reads the take back as the thing being sung
  // (INV-NOTES-087).
  const BOOL isOverdub = overdub.value_or(false);
  [session setCategory:AVAudioSessionCategoryPlayAndRecord
                  mode:isOverdub ? AVAudioSessionModeVoiceChat
                                 : AVAudioSessionModeMeasurement
               options:AVAudioSessionCategoryOptionDefaultToSpeaker |
                       AVAudioSessionCategoryOptionAllowBluetooth
                 error:&sessionErr];
  if (sessionErr) {
    [self emitState:@"error"];
    reject(@"session_failed", sessionErr.localizedDescription, sessionErr);
    return;
  }
  [session setActive:YES error:&sessionErr];
  if (sessionErr) {
    [self emitState:@"error"];
    reject(@"session_failed", sessionErr.localizedDescription, sessionErr);
    return;
  }
  // Voice-chat mode sends output to the receiver — the earpiece — whatever
  // the category options asked for. Overdubbing that way plays the take into
  // the side of the singer's head at conversation volume, which is
  // indistinguishable from it not playing at all (INV-NOTES-089).
  if (isOverdub) {
    [self followTheEar:YES];
  }

  _engine = [[AVAudioEngine alloc] init];
  AVAudioInputNode *input = _engine.inputNode;
  AVAudioFormat *hwFormat = [input outputFormatForBus:0];

  // Build the (re)usable C++ engine. configure() sizes the ring buffer and is
  // called here, off the audio thread, exactly as the engine requires.
  {
    std::lock_guard<std::mutex> lock(_pitchMutex);
    _config.sampleRateHz = hwFormat.sampleRate > 0 ? hwFormat.sampleRate : _config.sampleRateHz;
    _pitch = std::make_shared<PitchEngine>();
    _pitch->configure(_config);
    _samples.clear();
  }

  // Capture file for the RecordingHandle uri.
  //
  // The directory comes from the caller (files.ts) rather than being chosen
  // here. NSTemporaryDirectory() was the previous home, and the system is free
  // to reclaim it — which would leave a saved note pointing at audio that had
  // silently vanished. INV-PITCH-011.
  _recordingId = [[NSUUID UUID] UUIDString];
  NSURL *captureURL = nil;
  _captureFile =
      MicdrpOpenCaptureFile(captureDir, _recordingId, hwFormat, &captureURL);
  _captureURL = captureURL;

  __weak AudioEngineModule *weakSelf = self;
  [input installTapOnBus:0
              bufferSize:(AVAudioFrameCount)_config.hopSize
                  format:hwFormat
                   block:^(AVAudioPCMBuffer *buffer, AVAudioTime *when) {
    AudioEngineModule *strongSelf = weakSelf;
    if (!strongSelf) return;
    [strongSelf processBuffer:buffer];
  }];

  _startHostTime = NowMs();
  _lastEmitMs = 0;

  NSError *startErr = nil;
  [_engine prepare];
  if (![_engine startAndReturnError:&startErr]) {
    [input removeTapOnBus:0];
    _engine = nil;
    [self emitState:@"error"];
    reject(@"engine_failed", startErr.localizedDescription, startErr);
    return;
  }

  _running = true;
  [self startDraining];
  [self emitState:@"recording"];
  resolve(nil);
}

// Runs the analysis off the audio thread.
//
// The audio callback only enqueues PCM into a lock-free ring; everything
// expensive happens here. That is the whole reason for the shared engine: MPM
// over a 2048-sample window on the audio thread is work the callback has no
// deadline slack for, and a callback that runs late is a gap in the recording.
- (void)startDraining {
  _draining = true;
  std::shared_ptr<PitchEngine> engine = _pitch;
  __weak AudioEngineModule *weakSelf = self;
  _drain = std::thread([weakSelf, engine]() {
    while (true) {
      AudioEngineModule *strongSelf = weakSelf;
      if (!strongSelf || !strongSelf->_draining.load()) {
        return;
      }
      [strongSelf drainOnce];
      // A hop at 44.1kHz is ~23ms; waking at half that keeps the ring shallow
      // without spinning.
      std::this_thread::sleep_for(std::chrono::milliseconds(10));
    }
  });
}

/** Take whatever windows are ready, and emit the newest at the throttled rate. */
- (void)drainOnce {
  std::shared_ptr<PitchEngine> engine;
  {
    std::lock_guard<std::mutex> lock(_pitchMutex);
    engine = _pitch;
  }
  if (!engine) {
    return;
  }
  std::vector<PitchSample> emitted;
  while (auto s = engine->tryAnalyze()) {
    std::lock_guard<std::mutex> lock(_pitchMutex);
    _samples.push_back(*s);
    emitted.clear();
    emitted.push_back(*s);
  }
  if (emitted.empty()) {
    return;
  }
  [self emitThrottled:emitted];
}

// Real-time audio thread. Enqueue only: the ring is lock-free and never
// allocates, so this cannot block or wait on the drain.
- (void)processBuffer:(AVAudioPCMBuffer *)buffer {
  const AVAudioFrameCount frameCount = buffer.frameLength;
  float *const *channels = buffer.floatChannelData;
  if (channels == nullptr || frameCount == 0) {
    return;
  }
  const float *mono = channels[0];

  // Persist raw audio (best-effort; ignore errors on the audio thread).
  if (_captureFile != nil) {
    [_captureFile writeFromBuffer:buffer error:nil];
  }

  std::shared_ptr<PitchEngine> engine = std::atomic_load(&_pitch);
  if (engine) {
    engine->push(mono, (std::size_t)frameCount);
  }
}

- (void)emitThrottled:(const std::vector<PitchSample> &)emitted {
  if (emitted.empty()) {
    return;
  }

  // Throttle JS emission to ~emitRateHz.
  const double now = NowMs();
  const double minIntervalMs = 1000.0 / (_config.emitRateHz > 0 ? _config.emitRateHz : 60.0);
  if (now - _lastEmitMs < minIntervalMs) {
    return;
  }
  _lastEmitMs = now;

  const PitchSample &s = emitted.back();
  NSDictionary *body = @{
    @"timestampMs": @(s.timestampMs),
    @"frequencyHz": @(s.frequencyHz),
    @"clarity": @(s.clarity),
    @"levelDb": @(s.levelDb),
    @"centroidHz": @(s.centroidHz),
    @"flatness": @(s.flatness),
    @"rolloffHz": @(s.rolloffHz),
    @"fluxDb": @(s.fluxDb),
    @"midi": (s.voiced ? @(s.midi) : (id)[NSNull null]),
    @"cents": (s.voiced ? @(s.cents) : (id)[NSNull null]),
  };
  [self emitOnPitch:body];
}

/**
 * The round trip from asking for a sound to hearing it back through the mic.
 *
 * Output path, plus input path, plus the buffer the engine works in — the
 * three delays a voice sung against playback actually passes through. Read
 * from the session at the moment of asking rather than assumed: the built-in
 * speaker, wired headphones and Bluetooth differ, and Bluetooth by enough
 * that a constant would be wrong everywhere but where it was measured
 * (INV-NOTES-074).
 *
 * Zero when the session will not say, which the caller must treat as "do not
 * correct" rather than "no latency" — a wrong correction is worse than none.
 */
- (void)roundTripLatencyMs:(RCTPromiseResolveBlock)resolve
                    reject:(__unused RCTPromiseRejectBlock)reject {
  AVAudioSession *session = [AVAudioSession sharedInstance];
  NSTimeInterval seconds =
      session.outputLatency + session.inputLatency + session.IOBufferDuration;
  resolve(@(seconds > 0 ? seconds * 1000.0 : 0.0));
}

/**
 * Speaker at arm's length, earpiece against the head — the way a call behaves.
 *
 * Singing a part against a take is done both ways: held out while working on
 * the phrase, and up to the ear in a room where a speaker would be rude or
 * would bleed into the microphone. Asking which one to use would be a setting
 * about where the phone is, which the phone already knows (INV-NOTES-090).
 *
 * The proximity sensor sits by the earpiece and iOS reports it as a device
 * state. On a device without one — an iPad — enabling it does nothing and no
 * notification ever arrives, so the speaker override stands and the behaviour
 * is exactly what it was.
 */
- (void)dealloc {
  // The drain thread holds a weak reference to self and checks it every wake,
  // but a thread still running while its object is torn down is a race worth
  // closing here rather than reasoning about.
  _draining = false;
  if (_drain.joinable()) {
    _drain.join();
  }
  // Synchronously, and without dispatching: handing `self` to another queue
  // from dealloc hands it an object that is already going away.
  [[NSNotificationCenter defaultCenter]
      removeObserver:self
                name:UIDeviceProximityStateDidChangeNotification
              object:nil];
}

- (void)followTheEar:(BOOL)following {
  dispatch_async(dispatch_get_main_queue(), ^{
    UIDevice *device = [UIDevice currentDevice];
    NSNotificationCenter *centre = [NSNotificationCenter defaultCenter];
    if (!following) {
      [centre removeObserver:self
                        name:UIDeviceProximityStateDidChangeNotification
                      object:nil];
      device.proximityMonitoringEnabled = NO;
      return;
    }
    device.proximityMonitoringEnabled = YES;
    [centre addObserver:self
               selector:@selector(proximityChanged:)
                   name:UIDeviceProximityStateDidChangeNotification
                 object:nil];
    [self routeForProximity];
  });
}

- (void)proximityChanged:(__unused NSNotification *)note {
  [self routeForProximity];
}

/** Near the face, the receiver; away from it, the speaker. */
- (void)routeForProximity {
  const BOOL atTheEar = [UIDevice currentDevice].proximityState;
  AVAudioSession *session = [AVAudioSession sharedInstance];
  [session overrideOutputAudioPort:atTheEar
                                       ? AVAudioSessionPortOverrideNone
                                       : AVAudioSessionPortOverrideSpeaker
                             error:nil];
}

- (void)stop:(RCTPromiseResolveBlock)resolve
      reject:(RCTPromiseRejectBlock)reject {
  if (!_running.load()) {
    reject(@"not_running", @"AudioEngine is not running", nil);
    return;
  }
  [self emitState:@"analyzing"];

  AVAudioInputNode *input = _engine.inputNode;
  [input removeTapOnBus:0];
  [_engine stop];
  _engine = nil;
  _running = false;

  // Stop the drain, then take whatever the ring still holds. Skipping this
  // would lose the tail of the take — every window pushed since the last
  // wake-up, which is exactly the end of the singing.
  _draining = false;
  if (_drain.joinable()) {
    _drain.join();
  }
  [self drainOnce];
  // The sensor is only wanted while something is playing to be held up to.
  [self followTheEar:NO];

  const double durationMs = NowMs() - _startHostTime;

  NSMutableArray *samplesOut = [NSMutableArray array];
  double sampleRate = _config.sampleRateHz;
  {
    std::lock_guard<std::mutex> lock(_pitchMutex);
    for (const PitchSample &s : _samples) {
      [samplesOut addObject:@{
        @"timestampMs": @(s.timestampMs),
        @"frequencyHz": @(s.frequencyHz),
        @"clarity": @(s.clarity),
        @"levelDb": @(s.levelDb),
        @"centroidHz": @(s.centroidHz),
    @"flatness": @(s.flatness),
    @"rolloffHz": @(s.rolloffHz),
    @"fluxDb": @(s.fluxDb),
    @"centroidHz": @(s.centroidHz),
    @"flatness": @(s.flatness),
    @"rolloffHz": @(s.rolloffHz),
    @"fluxDb": @(s.fluxDb),
        @"midi": (s.voiced ? @(s.midi) : (id)[NSNull null]),
        @"cents": (s.voiced ? @(s.cents) : (id)[NSNull null]),
      }];
    }
    _pitch.reset();
  }

  _captureFile = nil;  // flushes + closes
  NSString *uri = _captureURL ? _captureURL.absoluteString : @"";

  NSDictionary *handle = @{
    @"id": _recordingId ?: [[NSUUID UUID] UUIDString],
    @"uri": uri,
    @"sampleRateHz": @(sampleRate),
    @"durationMs": @(durationMs),
    @"samples": samplesOut,
  };

  [self emitState:@"idle"];
  resolve(handle);
}

@end
