#!/bin/sh
# bump-version.sh — update VERSION_NUMBER and BUILD_NUMBER in all .env files
# and in the iOS xcconfig used as a source of truth.
#
# Usage:
#   scripts/bump-version.sh --version 1.2.3 --build 42
#   scripts/bump-version.sh --build 43          # keep version, bump build only
#
# The script operates relative to the repository root regardless of cwd.
#
# POSIX sh, shellcheck-clean.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CLIENT_DIR="${REPO_ROOT}/packages/client"

# ---------------------------------------------------------------------------
# Defaults (overridden by flags)
# ---------------------------------------------------------------------------
NEW_VERSION=""
NEW_BUILD=""

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
while [ "$#" -gt 0 ]; do
  case "$1" in
    --version|-v)
      NEW_VERSION="$2"
      shift 2
      ;;
    --build|-b)
      NEW_BUILD="$2"
      shift 2
      ;;
    *)
      echo "Unknown argument: $1" >&2
      echo "Usage: $0 [--version X.Y.Z] [--build N]" >&2
      exit 1
      ;;
  esac
done

if [ -z "${NEW_VERSION}" ] && [ -z "${NEW_BUILD}" ]; then
  echo "Error: at least one of --version or --build must be provided." >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Helper: portable in-place sed (BSD / GNU compatible)
# ---------------------------------------------------------------------------
replace_in_file() {
  # replace_in_file <file> <pattern> <replacement>
  local file="$1"
  local pattern="$2"
  local replacement="$3"

  if [ ! -f "${file}" ]; then
    echo "Warning: file not found, skipping: ${file}" >&2
    return 0
  fi

  # BSD sed (macOS) requires an explicit extension argument to -i; GNU sed accepts -i ''
  if sed --version 2>/dev/null | grep -q "GNU"; then
    sed -i "s|${pattern}|${replacement}|g" "${file}"
  else
    sed -i '' "s|${pattern}|${replacement}|g" "${file}"
  fi
}

# ---------------------------------------------------------------------------
# Update .env files (used by react-native-config)
# ---------------------------------------------------------------------------
for env_file in \
    "${CLIENT_DIR}/.env.development" \
    "${CLIENT_DIR}/.env.staging" \
    "${CLIENT_DIR}/.env.production"; do

  if [ ! -f "${env_file}" ]; then
    echo "Skipping missing file: ${env_file}"
    continue
  fi

  if [ -n "${NEW_VERSION}" ]; then
    replace_in_file "${env_file}" "VERSION_NUMBER=.*" "VERSION_NUMBER=${NEW_VERSION}"
    echo "  [env] VERSION_NUMBER=${NEW_VERSION} → ${env_file}"
  fi

  if [ -n "${NEW_BUILD}" ]; then
    replace_in_file "${env_file}" "BUILD_NUMBER=.*" "BUILD_NUMBER=${NEW_BUILD}"
    echo "  [env] BUILD_NUMBER=${NEW_BUILD} → ${env_file}"
  fi
done

# ---------------------------------------------------------------------------
# Update iOS xcconfig (VERSION_NUMBER / BUILD_NUMBER)
# Info.plist reads $(VERSION_NUMBER) and $(BUILD_NUMBER) from the xcconfig
# chain at build time.
# ---------------------------------------------------------------------------
IOS_XCCONFIG="${CLIENT_DIR}/ios/env.xcconfig"

# env.xcconfig only includes tmp.xcconfig at runtime; the version values live
# in the .env files picked up by react-native-config.  We additionally write a
# dedicated release.xcconfig so xcodebuild can be called without a Metro server.

RELEASE_XCCONFIG="${CLIENT_DIR}/ios/release.xcconfig"

{
  printf "// Auto-generated by scripts/bump-version.sh — do not hand-edit.\n"
  if [ -n "${NEW_VERSION}" ]; then
    printf "VERSION_NUMBER = %s\n" "${NEW_VERSION}"
  fi
  if [ -n "${NEW_BUILD}" ]; then
    printf "BUILD_NUMBER = %s\n" "${NEW_BUILD}"
  fi
} > "${RELEASE_XCCONFIG}"

echo "  [ios] Written: ${RELEASE_XCCONFIG}"

# ---------------------------------------------------------------------------
# Update Android version in the primary .env.production (versionCode /
# versionName are injected by react-native-config via project.env.get() in
# build.gradle; we already updated the .env files above).
# ---------------------------------------------------------------------------
echo "  [android] versionCode/versionName updated via .env files (react-native-config)."

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
echo ""
echo "Version bump complete."
[ -n "${NEW_VERSION}" ] && echo "  VERSION_NUMBER = ${NEW_VERSION}"
[ -n "${NEW_BUILD}" ]   && echo "  BUILD_NUMBER   = ${NEW_BUILD}"
